apiVersion: 1
policies:
  - orgId: 1
    receiver: QuizApp Email
    group_by: [alertname, severity]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: QuizApp Email
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 2m
        repeat_interval: 1h
      - receiver: QuizApp Email
        matchers:
          - severity = warning
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 6h
