global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quizapp-backend'
    scheme: https
    static_configs:
      - targets: ['quizapp-backend-smaya2026.azurewebsites.net']
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: false
